name: nsm
version: '1.0'
summary: (static) site manager/generator
license: MIT
description: |
  nsm is a cross-platform open source git-like
  and LaTeX-like command-line dynamic/static site
  generator and dynamic/static site manager. 
  See https://nift.cc.

confinement: strict
base: core18

parts:
  nsm:
    plugin: make
    source-type: tar
    source: https://github.com/nifty-site-manager/nsm-snap/raw/master/nsm.tar
    build-packages:
    - g++
    stage-packages:
    - git-core

apps:
  nsm:
    command: nsm
    plugs:
      - home
      - removable-media
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      DISABLE_WAYLAND: '1'
      GIT_TEMPLATE_DIR: $SNAP/usr/share/git-core/templates
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core
