name: nsm
version: '1.0'
summary: (static) site manager/generator
license: MIT
description: |
  nsm is a cross-platform open source git-like
  and LaTeX-like command-line (static) site
  manager/generator. See https://nift.cc.

confinement: devmode
base: core18

parts:
  nsm:
    plugin: make
    source-type: tar
    source: https://github.com/nifty-site-manager/nsm-snap/raw/master/nsm.tar
    build-packages:
    - g++
    stage-packages:
    - curl-devel
    - libcurl4-openssl-dev 
    - git

apps:
  nsm:
    command: nsm
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      DISABLE_WAYLAND: '1'
