name: nsm
version: '2.1'
summary: website generator
license: MIT
description: |
  `snap install nsm`
  
  Nift (aka nsm) is a cross-platform open source 
  CLI website generator. See https://nift.cc.

confinement: strict
base: core18

parts:
  nsm:
    plugin: make
    source-type: zip
    source: https://github.com/nifty-site-manager/nsm-snap/raw/master/nsm.zip
    build-packages:
    - g++
    stage-packages:
    - git-core

apps:
  luajit:
    command: luajit
    plugs:
      - home
      - removable-media
      - network
      - network-bind
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      DISABLE_WAYLAND: '1'
      GIT_TEMPLATE_DIR: $SNAP/usr/share/git-core/templates
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core
  libluajit:
    command: libluajit-5.1.so.2
    plugs:
      - home
      - removable-media
      - network
      - network-bind
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      DISABLE_WAYLAND: '1'
      GIT_TEMPLATE_DIR: $SNAP/usr/share/git-core/templates
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core
  nsm:
    command: nsm
    plugs:
      - home
      - removable-media
      - network
      - network-bind
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      DISABLE_WAYLAND: '1'
      GIT_TEMPLATE_DIR: $SNAP/usr/share/git-core/templates
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core
  nift:
    command: nift
    plugs:
      - home
      - removable-media
      - network
      - network-bind
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      DISABLE_WAYLAND: '1'
      GIT_TEMPLATE_DIR: $SNAP/usr/share/git-core/templates
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core
